In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\r.vardhan.reddy\Desktop\Data\adult.csv')
df.sample(5)

39  State-gov   77516      Bachelors   13        Never-married  \
17092  36    Private  152307        HS-grad    9   Married-civ-spouse   
20845  30    Private   32008      Bachelors   13        Never-married   
24857  54    Private  143822   Some-college   10   Married-civ-spouse   
12584  20    Private  296618        HS-grad    9        Never-married   
20344  19    Private  216647   Some-college   10        Never-married   

             Adm-clerical   Not-in-family   White     Male   2174   0   40  \
17092   Machine-op-inspct         Husband   White     Male      0   0   40   
20845        Tech-support   Not-in-family   White   Female      0   0   72   
24857        Craft-repair         Husband   White     Male      0   0   45   
12584               Sales   Not-in-family   White   Female      0   0   30   
20344       Other-service   Not-in-family   White   Female      0   0   30   

        United-States   <=50K  
17092   United-States   <=50K  
20845   United-States   <=50K  
24857   United-States    >50K  
12584   United-States   <=50K  
20344   United-States   <=50K

In [3]:
df.isnull().sum()

39                0
 State-gov        0
 77516            0
 Bachelors        0
 13               0
 Never-married    0
 Adm-clerical     0
 Not-in-family    0
 White            0
 Male             0
 2174             0
 0                0
 40               0
 United-States    0
 <=50K            0
dtype: int64

In [4]:
## SImple Imputer
from sklearn.impute import SimpleImputer
si = SimpleImputer()

In [5]:
df.columns

Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

In [6]:
si.fit_transform(df[['39']])

array([[50.],
       [38.],
       [53.],
       ...,
       [58.],
       [22.],
       [52.]])

In [7]:
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [8]:
df.nunique()

39                   73
 State-gov            9
 77516            21647
 Bachelors           16
 13                  16
 Never-married        7
 Adm-clerical        15
 Not-in-family        6
 White                5
 Male                 2
 2174               119
 0                   92
 40                  94
 United-States       42
 <=50K                2
dtype: int64

In [9]:
## Ordinal Encoding

In [10]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [11]:
df[' Male'].value_counts()

 Male      21789
 Female    10771
Name:  Male, dtype: int64

In [12]:
oe = OrdinalEncoder(categories = [[' Male',' Female']])
oe.fit_transform(df[[' Male']])

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [0.],
       [1.]])

In [13]:
df_Male = oe.fit_transform(df[[' Male']])

In [14]:
df[' White'].value_counts()

 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name:  White, dtype: int64

In [15]:
## OneHotEncoding White
ohe = OneHotEncoder(drop='first',sparse=False, dtype=np.int32)



In [16]:
 ohe.fit_transform(df[[' White']])

array([[0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       ...,
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [17]:
df_White = ohe.fit_transform(df[[' White']])

In [18]:
df_White.shape

(32560, 4)

In [19]:
## Extracting all other columns to append

In [20]:
 df.drop(columns=[' White',' Male'])

39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse   
1      38            Private  215646      HS-grad    9             Divorced   
2      53            Private  234721         11th    7   Married-civ-spouse   
3      28            Private  338409    Bachelors   13   Married-civ-spouse   
4      37            Private  284582      Masters   14   Married-civ-spouse   
...    ..                ...     ...          ...  ...                  ...   
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40            Private  154374      HS-grad    9   Married-civ-spouse   
32557  58            Private  151910      HS-grad    9              Widowed   
32558  22            Private  201490      HS-grad    9        Never-married   
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

             Adm-clerical   Not-in-family   2174   0   40   United-States  \
0         Exec-managerial         Husband      0   0   13   United-States   
1       Handlers-cleaners   Not-in-family      0   0   40   United-States   
2       Handlers-cleaners         Husband      0   0   40   United-States   
3          Prof-specialty            Wife      0   0   40            Cuba   
4         Exec-managerial            Wife      0   0   40   United-States   
...                   ...             ...    ...  ..  ...             ...   
32555        Tech-support            Wife      0   0   38   United-States   
32556   Machine-op-inspct         Husband      0   0   40   United-States   
32557        Adm-clerical       Unmarried      0   0   40   United-States   
32558        Adm-clerical       Own-child      0   0   20   United-States   
32559     Exec-managerial            Wife  15024   0   40   United-States   

        <=50K  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32555   <=50K  
32556    >50K  
32557   <=50K  
32558   <=50K  
32559    >50K  

[32560 rows x 13 columns]

In [21]:
df_others = df.drop(columns=[' White',' Male'])

In [22]:
np.concatenate((df_others,df_White,df_Male),axis=1)

array([[50, ' Self-emp-not-inc', 83311, ..., 0, 1, 0.0],
       [38, ' Private', 215646, ..., 0, 1, 0.0],
       [53, ' Private', 234721, ..., 0, 0, 0.0],
       ...,
       [58, ' Private', 151910, ..., 0, 1, 1.0],
       [22, ' Private', 201490, ..., 0, 1, 0.0],
       [52, ' Self-emp-inc', 287927, ..., 0, 1, 1.0]], dtype=object)

In [23]:
df_transformed = np.concatenate((df_others,df_White,df_Male),axis=1)

In [24]:
df_transformed

array([[50, ' Self-emp-not-inc', 83311, ..., 0, 1, 0.0],
       [38, ' Private', 215646, ..., 0, 1, 0.0],
       [53, ' Private', 234721, ..., 0, 0, 0.0],
       ...,
       [58, ' Private', 151910, ..., 0, 1, 1.0],
       [22, ' Private', 201490, ..., 0, 1, 0.0],
       [52, ' Self-emp-inc', 287927, ..., 0, 1, 1.0]], dtype=object)

In [25]:
df_transformed.shape

(32560, 18)

In [26]:
df.shape

(32560, 15)

## Column Transformer

In [27]:
from sklearn.compose import ColumnTransformer

In [28]:
transformers = ColumnTransformer(transformers=[
    ("tf1" ,OrdinalEncoder(categories = [[' Male',' Female']]),[' Male']),
    ("tf2",OneHotEncoder(drop='first',sparse=False, dtype=np.int32),[' White'])
],remainder = 'passthrough')

In [30]:
df_columnTransformer = transformers.fit_transform(df)

In [31]:
transformers.fit_transform(df)

array([[0.0, 0, 0, ..., 13, ' United-States', ' <=50K'],
       [0.0, 0, 0, ..., 40, ' United-States', ' <=50K'],
       [0.0, 0, 1, ..., 40, ' United-States', ' <=50K'],
       ...,
       [1.0, 0, 0, ..., 40, ' United-States', ' <=50K'],
       [0.0, 0, 0, ..., 20, ' United-States', ' <=50K'],
       [1.0, 0, 0, ..., 40, ' United-States', ' >50K']], dtype=object)

In [33]:
df_columnTransformer.shape

(32560, 18)

In [35]:
df_transformed.shape

(32560, 18)